In [1]:




%run ./"0 Imports and functions.ipynb"
gc.collect()
files,distance,r = ['HCN_J1-0.cube.fits'],3.5*u.Mpc,33*u.deg
#files,distance,r = ["CMZ_3mm_HCN.fits"],8170*u.pc,0*u.deg

sc = SpectralCube.read("Spectral Cubes/"+files[0]) 


#def Crop_Around_Center(sc,rotation_angle,center,desired_fov,distance)
#center = SkyCoord('-00d03m20.76s  ', '-00d02m46.176s', frame='galactic')
center=SkyCoord('00h47m33.14s' ,'-25d17m17.52s',frame='icrs') #the center of NGC253
#print(dir(center))
print((center))
print(str(center))

            
print(center.ra.hms)
hms=center.ra.hms
print(f"{int(hms.h)}h{int(hms.m)}m{(hms.s)}s")
print(type(center.ra))
print(center.dec)
#new_sc,o,f=Crop_Around_Center(sc,r,center,[70,360]*u.pc,distance)
#print(new_sc,o,f)
#new_sc.write("Test.fits",overwrite=True)


/home/ben/miniconda3/bin/python
3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
astropy 5.1.dev153+gb740594dc
spectral_cube 0.6.1.dev22+g003ef16
spectral_cube file path /home/ben/.local/lib/python3.8/site-packages/spectral_cube/__init__.py
reproject 0.8
1.23.1 Numpy
astrodendro_file: /home/ben/.local/lib/python3.8/site-packages/astrodendro/__init__.py
Results will be saved to Directory ./Result Files
Cubes will be saved and loaded with Directory ./Spectral Cubes
Plots will be saved to Directory ./Plots
Dendrograms will be saved to Directory ./Dendrograms
<SkyCoord (ICRS): (ra, dec) in deg
    (11.88808333, -25.2882)>
<SkyCoord (ICRS): (ra, dec) in deg
    (11.88808333, -25.2882)>
hms_tuple(h=0.0, m=47.0, s=33.14000000000064)
0h47m33.14000000000064s
<class 'astropy.coordinates.angles.Longitude'>
-25d17m17.52s


In [5]:
# rotate NGC253
###################################################################################################
sc = SpectralCube.read("Spectral Cubes/"+files[0])[50:55,0:200,0:200]

# rotation matrix for 33 degree
rotation_matrix = {'PC1_1':  8.386705679454E-01,
                   'PC2_1': -5.446390350150E-01,
                   'PC3_1':  0.000000000000E+00,
                   'PC1_2': 5.446390350150E-01,
                   'PC2_2':  8.386705679454E-01,
                   'PC3_2':  0.000000000000E+00,
                   'PC1_3':  0.000000000000E+00,
                   'PC2_3':  0.000000000000E+00,
                   'PC3_3':  1.000000000000E+00}

reheader = copy.deepcopy(sc.header)
for key,val in rotation_matrix.items():
    reheader[key] = val

# rotate by regridding onto rotated header
sc = SpectralCube.read(sc.hdu)
sc.allow_huge_operations = True
cube6 = sc.reproject(reheader, order='bilinear', use_memmap=True, filled=True)
cube6 = SpectralCube.read(cube6.hdu)
cube6.write("Test.fits",overwrite=True)


In [9]:
from scipy.spatial.transform import Rotation as R
import numpy as np

print(scipy.__version__)
r = R.from_quat([0, 0, np.sin(np.pi/4), np.cos(np.pi/4)])
print(r.as_dcm())

r = R.from_euler('z', 33, degrees=True)

print(r.as_dcm())


1.3.3
[[ 2.22044605e-16 -1.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  2.22044605e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 0.83867057 -0.54463904  0.        ]
 [ 0.54463904  0.83867057  0.        ]
 [ 0.          0.          1.        ]]
